# Generated by Django 5.1.2 on 2025-05-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chat', '0003_roommessagesmodel_roommodel_and_more'),
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='CustomUserModel',
        ),
    ]
