# Generated by Django 5.1.2 on 2025-10-23 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_rename_customusermodel_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_activity',
            field=models.DateTimeField(blank=True, help_text='Last time the user was active', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='Required 20 characters or fewer. Letters, digits and _ only.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username can only contain letters, numbers, and underscores', regex='^[a-zA-Z0-9_]+$')]),
        ),
    ]
