# Generated by Django 5.1.2 on 2025-05-15 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['user', 'recipient'], name='chat_messag_user_id_b7194c_idx'),
        ),
        migrations.AddIndex(
            model_name='messages',
            index=models.Index(fields=['is_read'], name='chat_messag_is_read_6e9c3b_idx'),
        ),
    ]
