# Generated by Django 5.1.2 on 2025-05-17 16:10

import chat.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMessagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RoomModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(default='default.jpg', help_text='Profile picture (300x300 recommended)', upload_to=chat.models.userDirectoryPath)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RenameModel(
            old_name='Messages',
            new_name='MessagesModel',
        ),
        migrations.RenameIndex(
            model_name='messagesmodel',
            new_name='chat_messag_user_id_949938_idx',
            old_name='chat_messag_user_id_b7194c_idx',
        ),
        migrations.RenameIndex(
            model_name='messagesmodel',
            new_name='chat_messag_is_read_2d120b_idx',
            old_name='chat_messag_is_read_6e9c3b_idx',
        ),
        migrations.AddField(
            model_name='roommessagesmodel',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_of_room', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roommodel',
            name='participants',
            field=models.ManyToManyField(related_name='room_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roommessagesmodel',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.roommodel'),
        ),
    ]
