# Generated by Django 5.1.2 on 2025-05-17 16:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_roommessagesmodel_roommodel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessagesModel',
            new_name='Messages',
        ),
        migrations.RenameIndex(
            model_name='messages',
            new_name='chat_messag_user_id_b7194c_idx',
            old_name='chat_messag_user_id_949938_idx',
        ),
        migrations.RenameIndex(
            model_name='messages',
            new_name='chat_messag_is_read_6e9c3b_idx',
            old_name='chat_messag_is_read_2d120b_idx',
        ),
    ]
