# Generated by Django 5.1.2 on 2025-11-28 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_message_messages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelTable(
            name='messages',
            table='messages',
        ),
    ]
